### ISSUE TITLE
WARNING Invalid token.

### ISSUE THREAD

**Issue by Fespinoza831** [tmknight/docker-nordvpn#75] opened 2023-09-21 21:06 UTC
Hello, My container keeps shutting down stating invalid token. I already generated a new token but the issue continues. The issue just started this morning.

**Comment by tmknight** [comment] 2023-09-21 23:17
Is this your first experience with this project or have you been a long time user and this is new behavior?

**Comment by Fespinoza831** [comment] 2023-09-21 23:47
Long time user and this is the first time it happened.

**Comment by tmknight** [comment] 2023-09-22 13:50
I see this from time to time with recent releases of NordVPN, however, not to the point the container is unusable.  The code that generates this warning is simple: https://github.com/search?q=repo%3Atmknight%2Fdocker-nordvpn%20invalid%20token&type=code

When you are seeing this warning; you can test by running the image as is with entrypoint to bash, start the daemon and login to see if different results.

**Comment by tmknight** [comment] 2023-10-22 11:51
Closing due to inability to reproduce with any significantly impacting effect or that could be resolved by change in overlying code (i.e. this is nordVPN being nordVPN).

**Closed by tmknight** 2023-10-22 11:51 UTC
